### ISSUE TITLE
LabelEncoder()

### ISSUE THREAD

**Issue by weili1988** [Jungyhuk/Latent-Attention#1]
Where is the LabelEncoder() that can be used to map prediction numbers to real instructions. 
E.G. 
'label_names': ['Instagram',
   'Instagram.Any_new_photo_by_you',
   'Dropbox',
   'Dropbox.Add_file_from_URL'],
  'labels': [45, 193, 11, 20],

Where can I find the map between label_names and labels ? 

Thanks a lot. I am trying to use your code to play with prediction.

**Comment by Jungyhuk** [comment]
It is in the pkl file in dataset/IFTTT (use the keyword "labeler" to find it). dataPreprocessor/process_IFTTT_data.py is the code that generates this pkl file, so you can refer to it for more details.
